version:     "020--10-Aug-2021"
copyright:   "2021-2021"
title:       "The Grounded Theory Page"
description:
  This is a
  Grounded Theory Page.
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "GTM"
  link:      "/GTM/"
- navbar:    "GitHub"
  link:      "https://github.com/cbkadal/gtm/"
- navbar:    "About"
  link:      "/ABOUT/"
- navbar:    "GitHub Page"
  link:      "https://gtm.vlsm.org/"
author:      "Chuck von manTeuffel"
address:     "Cologne, 50859"
markdown:    "kramdown"
sitemap:     "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
lang:        "en-US"
google_analytics: "UA-89852122-13"
github:
- metadata
defaults:
- scope:
    path: ""
  values:
    layout: "layout"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
